#!/bin/bash

alias bashp='vim ~/.bash_profile'
alias sbashp='source ~/.bash_profile'
alias bashr='vim ~/.bashrc'
alias sbashr='source ~/.bashrc'
alias vimr='vim ~/.vimrc'
alias basha='vim ~/.bash_aliases'
alias sbasha='source ~/.bash_aliases'
alias p='pwd'
alias c='clear'
alias ..='cd .. && ll'
alias .2='cd ../.. && ll'
alias .3='cd ../../.. && ll'
alias .4='cd ../../../.. && ll'
alias grep='grep --color=auto'
alias h='history'
alias l='ls'
alias ls='ls -GFh'
alias la='ls -a'
alias ll='ls -GAFhlp'
alias gitc='vim ~/dot_files/.gitconfig'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias path='echo -e ${PATH//:/\\n}'
alias space='du -sk * | sort -n | tail -10' # prints the top 10 largest directories/files in the current dir
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gpoh='git push origin head'
alias sr='git add . && git commit -m "Small refactoring" && gpoh'
alias lf='git add . && git commit -m "Linting fix" && gpoh'
alias gs='git status'
alias gb='git branch'
alias gcod='git checkout develop && git fetch && git pull && Pod install'
alias ldot='. "$HOME"/dot_files/load.sh'
alias cdot='. "$HOME"/dot_files/clean_up.sh'
alias fuxcode='rm -rf ~/Library/Developer/Xcode/DerivedData/ && printf "Xcode DerivedData deleted"'
alias cafe='caffeinate -dismu'
alias study='open https://leetcode.com/explore/ && open https://www.google.com/search?q=timer&rlz=1C5CHFA_enUS848US848&oq=timer&aqs=chrome..69i57j35i39j0l5j69i60.474j0j7&sourceid=chrome&ie=UTF-8 && open https://docs.google.com/forms/d/e/1FAIpQLSdNT8OzWVhQCltL9p07prhuYfNmqz-LCG5_Dk4Bzcq3GWkDwA/viewform && open https://docs.google.com/forms/d/1xKS3tIuIbUD6UbQJN6ZxXN92NreSAGpwFnQz4nnXxa0/edit'
